# Generated by Django 6.0.7 on 2026-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_studentenrollment_total_fee_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
