# Generated by Django 6.0.7 on 2026-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_coursebatch_courselesson_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='status',
            field=models.CharField(choices=[('approved', 'Verified & Approved'), ('pending', 'Pending Verification'), ('rejected', 'Declined / Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
