# Generated by Django 6.0.7 on 2026-08-31 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_link', models.URLField(help_text='Google Meet, Zoom, or Teams URL', max_length=500)),
                ('scheduled_at', models.DateTimeField(help_text='Scheduled date and time for the live class')),
                ('duration', models.CharField(default='1 Hour', max_length=50)),
                ('agenda', models.TextField(blank=True, help_text='Class outline, topics covered, or mentor instructions')),
                ('instructor_name', models.CharField(default='Qrious Tech Senior Mentor', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='accounts_app.coursebatch')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
