# Generated by Django 6.0.7 on 2026-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_liveclassschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
