# Generated by Django 6.0.7 on 2026-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_userprofile_avatar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='proof_image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
