# Generated by Django 6.0.7 on 2026-09-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_studentpayment_proof_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassschedule',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclassschedule',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Recorded Class Video Link (Google Drive, YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
    ]
