# Generated by Django 6.0.7 on 2026-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_fix_course_module_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='auto_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Optional future date and time to auto-publish this lesson', null=True),
        ),
        migrations.AddField(
            model_name='liveclassschedule',
            name='auto_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
