# Generated by Django 6.0.7 on 2026-09-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_courselesson_auto_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Homework questions, exam instructions, guidelines, and submission rules')),
                ('due_date', models.DateTimeField(help_text='Deadline for student submissions')),
                ('total_marks', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts_app.coursebatch')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(help_text='Student text response, code solution, essay, or answer script')),
                ('attachment_url', models.URLField(blank=True, help_text='Optional link to GitHub, Google Drive, Figma, etc.', max_length=500, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Pending Grading'), ('graded', 'Graded & Evaluated'), ('resubmit', 'Needs Revision')], default='submitted', max_length=20)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Mentor feedback, corrections, and evaluation notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts_app.studentenrollment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts_app.courseassignment')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'enrollment')},
            },
        ),
    ]
