# Generated by Django 6.0.7 on 2026-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0015_courseassignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='week_number',
            field=models.IntegerField(default=1, help_text='Week number e.g. 1, 2, 3...'),
        ),
    ]
