# Generated by Django 6.0.7 on 2026-09-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0016_courseassignment_week_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
