# Generated by Django 6.0.7 on 2026-08-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('total_found', models.IntegerField(default=0)),
                ('total_applied', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('log_output', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('applied', 'Applied ✅'), ('dry_run', 'Dry Run 🔵'), ('skipped', 'Skipped ⏭️'), ('failed', 'Failed ❌'), ('error', 'Error 💥'), ('already_applied', 'Already Applied ℹ️'), ('pending', 'Pending ⏳'), ('interview', 'Interview 🎉'), ('rejected', 'Rejected 😔'), ('offer', 'Offer Received 🏆')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('applicant_count', models.CharField(blank=True, max_length=100)),
                ('is_easy_apply', models.BooleanField(default=False)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
    ]
