# Generated by Django 6.0.7 on 2026-08-26 18:33

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('_password_token', models.TextField(db_column='password_token')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active ✅'), ('needs_verification', 'Needs Verification ⚠️'), ('inactive', 'Inactive ❌'), ('syncing', 'Syncing 🔄')], default='active', max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('profile_photo_url', models.URLField(blank=True, max_length=1000)),
                ('about', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('connections', models.CharField(blank=True, max_length=50)),
                ('session_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this resume', max_length=200)),
                ('file', models.FileField(upload_to=dashboard.models.resume_upload_path)),
                ('is_active', models.BooleanField(default=False, help_text='This is the resume the agent will use for applications')),
                ('file_size_kb', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='LinkedIn account this resume belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='dashboard.linkedinaccount')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
