# Generated by Django 6.0.7 on 2026-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_linkedinaccount_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='min_match_score',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='workplace_type',
            field=models.CharField(blank=True, default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_reasons',
            field=models.TextField(blank=True, help_text='Explanation and matching keywords'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.IntegerField(default=0, help_text='CV Match Score (0-100%)'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workplace_type',
            field=models.CharField(blank=True, default='', help_text='Remote / On-site / Hybrid', max_length=50),
        ),
    ]
