# Generated by Django 6.0.7 on 2026-09-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_agentrun_min_match_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='account',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentRun',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
